[package]
name = "tuirealm"
version = "1.8.0"
authors = ["Christian Visintin"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A tui-rs framework to build tui interfaces, inspired by React and Elm."
documentation = "https://docs.rs/tuirealm"
homepage = "https://github.com/veeso/tui-realm"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm"

[dependencies]
bitflags = "^1.3"
crossterm = { version = "^0.25", optional = true }
lazy-regex = "^2.3.0"
serde = { version = "^1", features = ["derive"], optional = true }
termion = { version = "^1.5", optional = true }
thiserror = "^1.0.0"
ratatui = { version = "0.22", default-features = false }
tuirealm_derive = { version = "^1.0.0", optional = true }

[dev-dependencies]
pretty_assertions = "^1.2.1"
toml = "0.5.9"
tempfile = "3.2.0"

[features]
default = ["derive", "with-crossterm"]
derive = ["tuirealm_derive"]
serialize = ["serde"]
with-crossterm = ["crossterm", "ratatui/crossterm"]
with-termion = ["termion", "ratatui/termion"]

[[example]]
name = "demo"
path = "examples/demo/demo.rs"

[[example]]
name = "user-events"
path = "examples/user_events/user_events.rs"
